spring:
  application:
    name: sc_server_user
  profiles:
    group:
      "dev": "repository-dev,service-dev,web-dev"
      "release": "repository-release,web-release,service-release"
    active: @activeProfiles@
    include: "repository,service,web"